version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start file:/data/database.db
    user: root
    tty: true
    stdin_open: true
    environment:
      SURREAL_USER: ${SURREAL_USER}
      SURREAL_PASS: ${SURREAL_PASS}
      SURREAL_AUTH: ${SURREAL_AUTH:-true}
      SURREAL_LOG: ${SURREAL_LOG:-info}
    networks:
      - caddy_public
    volumes:
      - db_data:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - ${NODE_PLACEMENT}
      labels:
        caddy: ${SURREAL_DOMAIN}
        caddy.encode: zstd gzip
        caddy.@ws.0_header: Connection *Upgrade*
        caddy.@ws.1_header: Upgrade websocket
        caddy.reverse_proxy_0: "{{upstreams 8000}}"
        caddy.reverse_proxy_0.header_up: "Host {host}"
        caddy.reverse_proxy_1: "@ws {{upstreams 8000}}"
        caddy.reverse_proxy_1.header_up: "Host {host}"

networks:
  caddy_public:
    external: true

volumes:
  db_data:
