version: '3.8'
name: surrealdb-dev

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start file:/data/database.db -A
    user: root
    tty: true
    stdin_open: true
    environment:
      SURREAL_USER: ${SURREAL_USER:-root}
      SURREAL_PASS: ${SURREAL_PASS:-root}
      SURREAL_AUTH: ${SURREAL_AUTH:-true}
      SURREAL_LOG: ${SURREAL_LOG:-info}
    volumes:
      - db_data:/data

volumes:
  db_data:
